package comcompletelee.naver.blog.codiforseoul;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.TextView;


/**
 * Created by hello world on 2015-12-23.
 */
public class OuterTable extends Activity {

    TextView blouson1;
    TextView blouson2;
    TextView blazerSS1;
    TextView blazerSS2;
    TextView blazerFW1;
    TextView blazerFW2;
    TextView leatherJacket1;
    TextView leatherJacket2;
    TextView mustang1;
    TextView mustang2;
    TextView coatSS1;
    TextView coatSS2;
    TextView coatFW1;
    TextView coatFW2;
    TextView paddingVest1;
    TextView paddingVest2;
    TextView paddingCoat1;
    TextView paddingCoat2;
    TextView fieldJacketSS1;
    TextView fieldJacketSS2;
    TextView fieldJacketFW1;
    TextView fieldJacketFW2;
    TextView deckJacket1;
    TextView deckJacket2;
    TextView litePadding1;
    TextView litePadding2;
    TextView duckPadding1;
    TextView duckPadding2;
    TextView n3b1;
    TextView n3b2;

    TextView test1;
    TextView test2;

    WeatherForecast todayOuter;
    int high;
    int low;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.outer);

;

        Intent intent = getIntent();

        todayOuter = (WeatherForecast) intent.getSerializableExtra("TODAY");


        blouson1 = (TextView) findViewById(R.id.Blouson1);
        blouson2 = (TextView) findViewById(R.id.Blouson2);
        blazerSS1 = (TextView) findViewById(R.id.blazerSS1);
        blazerSS2 = (TextView) findViewById(R.id.blazerSS2);
        blazerFW1 = (TextView) findViewById(R.id.blazerFW1);
        blazerFW2 = (TextView) findViewById(R.id.blazerFW2);
        leatherJacket1 = (TextView) findViewById(R.id.leatherJacket1);
        leatherJacket2 = (TextView) findViewById(R.id.leatherJacket2);
        mustang1 = (TextView) findViewById(R.id.mustang1);
        mustang2 = (TextView) findViewById(R.id.mustang2);
        coatSS1 = (TextView) findViewById(R.id.coatSS1);
        coatSS2 = (TextView) findViewById(R.id.coatSS2);
        coatFW1 = (TextView) findViewById(R.id.coatFW1);
        coatFW2 = (TextView) findViewById(R.id.coatFW2);
        paddingVest1 = (TextView) findViewById(R.id.paddingVest1);
        paddingVest2 = (TextView) findViewById(R.id.paddingVest2);
        paddingCoat1 = (TextView) findViewById(R.id.paddingCoat1);
        paddingCoat2 = (TextView) findViewById(R.id.paddingCoat2);
        fieldJacketSS1 = (TextView) findViewById(R.id.fieldJacketSS1);
        fieldJacketSS2 = (TextView) findViewById(R.id.fieldJacketSS2);
        fieldJacketFW1 = (TextView) findViewById(R.id.fieldJacketFW1);
        fieldJacketFW2 = (TextView) findViewById(R.id.fieldJacketFW2);
        deckJacket1 = (TextView) findViewById(R.id.deckJacket1);
        deckJacket2 = (TextView) findViewById(R.id.deckJacket2);
        litePadding1 = (TextView) findViewById(R.id.litePadding1);
        litePadding2 = (TextView) findViewById(R.id.litePadding2);
        duckPadding1 = (TextView) findViewById(R.id.duckPadding1);
        duckPadding2 = (TextView) findViewById(R.id.duckPadding2);
        n3b1 = (TextView) findViewById(R.id.n3b1);
        n3b2 = (TextView) findViewById(R.id.n3b2);


        low = todayOuter.getLow();
        high = todayOuter.getHigh();


        if (low >= 20)/*여름*/ {
            blouson1.setText("퇴각");
            blouson2.setText("퇴각");
            blazerSS1.setText("퇴각");
            blazerSS2.setText("퇴각");
            blazerFW1.setText("퇴각");
            blazerFW2.setText("퇴각");
            leatherJacket1.setText("퇴각");
            leatherJacket2.setText("퇴각");
            mustang1.setText("퇴각");
            mustang2.setText("퇴각");
            coatSS1.setText("퇴각");
            coatSS2.setText("퇴각");
            coatFW1.setText("퇴각");
            coatFW2.setText("퇴각");
            paddingVest1.setText("퇴각");
            paddingVest2.setText("퇴각");
            paddingCoat1.setText("퇴각");
            paddingCoat2.setText("퇴각");
            fieldJacketSS1.setText("퇴각");
            fieldJacketSS2.setText("퇴각");
            fieldJacketFW1.setText("퇴각");
            fieldJacketFW2.setText("퇴각");
            deckJacket1.setText("퇴각");
            deckJacket2.setText("퇴각");
            litePadding1.setText("퇴각");
            litePadding2.setText("퇴각");
            duckPadding1.setText("퇴각");
            duckPadding2.setText("퇴각");
            n3b1.setText("퇴각");
            n3b2.setText("퇴각");

            blouson1.setTextColor(Color.RED);
            blouson2.setTextColor(Color.RED);
            blazerSS1.setTextColor(Color.RED);
            blazerSS2.setTextColor(Color.RED);
            blazerFW1.setTextColor(Color.RED);
            blazerFW2.setTextColor(Color.RED);
            leatherJacket1.setTextColor(Color.RED);
            leatherJacket2.setTextColor(Color.RED);
            mustang1.setTextColor(Color.RED);
            mustang2.setTextColor(Color.RED);
            coatSS1.setTextColor(Color.RED);
            coatSS2.setTextColor(Color.RED);
            coatFW1.setTextColor(Color.RED);
            coatFW2.setTextColor(Color.RED);
            paddingVest1.setTextColor(Color.RED);
            paddingVest2.setTextColor(Color.RED);
            paddingCoat1.setTextColor(Color.RED);
            paddingCoat2.setTextColor(Color.RED);
            fieldJacketSS1.setTextColor(Color.RED);
            fieldJacketSS2.setTextColor(Color.RED);
            fieldJacketFW1.setTextColor(Color.RED);
            fieldJacketFW2.setTextColor(Color.RED);
            deckJacket1.setTextColor(Color.RED);
            deckJacket2.setTextColor(Color.RED);
            litePadding1.setTextColor(Color.RED);
            litePadding2.setTextColor(Color.RED);
            duckPadding1.setTextColor(Color.RED);
            duckPadding2.setTextColor(Color.RED);
            n3b1.setTextColor(Color.RED);
            n3b2.setTextColor(Color.RED);
        } else if (low >= 15 && low < 20)/*초여름, 늦여름*/ {
            blouson1.setText("출격");
            blouson2.setText("출격");
            blazerSS1.setText("출격");
            blazerSS2.setText("출격");
            blazerFW1.setText("퇴각");
            blazerFW2.setText("퇴각");
            leatherJacket1.setText("퇴각");
            leatherJacket2.setText("퇴각");
            mustang1.setText("퇴각");
            mustang2.setText("퇴각");
            coatSS1.setText("퇴각");
            coatSS2.setText("퇴각");
            coatFW1.setText("퇴각");
            coatFW2.setText("퇴각");
            paddingVest1.setText("퇴각");
            paddingVest2.setText("퇴각");
            paddingCoat1.setText("퇴각");
            paddingCoat2.setText("퇴각");
            fieldJacketSS1.setText("퇴각");
            fieldJacketSS2.setText("퇴각");
            fieldJacketFW1.setText("퇴각");
            fieldJacketFW2.setText("퇴각");
            deckJacket1.setText("퇴각");
            deckJacket2.setText("퇴각");
            litePadding1.setText("퇴각");
            litePadding2.setText("퇴각");
            duckPadding1.setText("퇴각");
            duckPadding2.setText("퇴각");
            n3b1.setText("퇴각");
            n3b2.setText("퇴각");

            blouson1.setTextColor(Color.BLUE);
            blouson2.setTextColor(Color.BLUE);
            blazerSS1.setTextColor(Color.BLUE);
            blazerSS2.setTextColor(Color.BLUE);
            blazerFW1.setTextColor(Color.RED);
            blazerFW2.setTextColor(Color.RED);
            leatherJacket1.setTextColor(Color.RED);
            leatherJacket2.setTextColor(Color.RED);
            mustang1.setTextColor(Color.RED);
            mustang2.setTextColor(Color.RED);
            coatSS1.setTextColor(Color.RED);
            coatSS2.setTextColor(Color.RED);
            coatFW1.setTextColor(Color.RED);
            coatFW2.setTextColor(Color.RED);
            paddingVest1.setTextColor(Color.RED);
            paddingVest2.setTextColor(Color.RED);
            paddingCoat1.setTextColor(Color.RED);
            paddingCoat2.setTextColor(Color.RED);
            fieldJacketSS1.setTextColor(Color.RED);
            fieldJacketSS2.setTextColor(Color.RED);
            fieldJacketFW1.setTextColor(Color.RED);
            fieldJacketFW2.setTextColor(Color.RED);
            deckJacket1.setTextColor(Color.RED);
            deckJacket2.setTextColor(Color.RED);
            litePadding1.setTextColor(Color.RED);
            litePadding2.setTextColor(Color.RED);
            duckPadding1.setTextColor(Color.RED);
            duckPadding2.setTextColor(Color.RED);
            n3b1.setTextColor(Color.RED);
            n3b2.setTextColor(Color.RED);
        } else if(low>=5&&low<15)/*환절기*/{
            if(high>=20){
                blouson1.setText("출격");
                blouson2.setText("출격");
                blazerSS1.setText("출격");
                blazerSS2.setText("출격");
                blazerFW1.setText("퇴각");
                blazerFW2.setText("퇴각");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("퇴각");
                mustang2.setText("퇴각");
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("퇴각");
                coatFW2.setText("퇴각");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("퇴각");
                paddingCoat2.setText("퇴각");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("퇴각");
                fieldJacketFW2.setText("퇴각");
                deckJacket1.setText("퇴각");
                deckJacket2.setText("퇴각");
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("퇴각");
                duckPadding2.setText("퇴각");
                n3b1.setText("퇴각");
                n3b2.setText("퇴각");

                blouson1.setTextColor(Color.BLUE);
                blouson2.setTextColor(Color.BLUE);
                blazerSS1.setTextColor(Color.BLUE);
                blazerSS2.setTextColor(Color.BLUE);
                blazerFW1.setTextColor(Color.RED);
                blazerFW2.setTextColor(Color.RED);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.RED);
                mustang2.setTextColor(Color.RED);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.RED);
                coatFW2.setTextColor(Color.RED);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.RED);
                paddingCoat2.setTextColor(Color.RED);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.RED);
                fieldJacketFW2.setTextColor(Color.RED);
                deckJacket1.setTextColor(Color.RED);
                deckJacket2.setTextColor(Color.RED);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.RED);
                duckPadding2.setTextColor(Color.RED);
                n3b1.setTextColor(Color.RED);
                n3b2.setTextColor(Color.RED);
            } else if(high>=10&&high<20) {
                blouson1.setText("출격");
                blouson2.setText("출격");
                blazerSS1.setText("출격");
                blazerSS2.setText("출격");
                blazerFW1.setText("퇴각");
                blazerFW2.setText("퇴각");
                leatherJacket1.setText("출격");
                leatherJacket2.setText("출격");
                mustang1.setText("퇴각");
                mustang2.setText("퇴각");
                coatSS1.setText("출격");
                coatSS2.setText("출격");
                coatFW1.setText("퇴각");
                coatFW2.setText("퇴각");
                paddingVest1.setText("출격");
                paddingVest2.setText("출격");
                paddingCoat1.setText("퇴각");
                paddingCoat2.setText("퇴각");
                fieldJacketSS1.setText("출격");
                fieldJacketSS2.setText("출격");
                fieldJacketFW1.setText("퇴각");
                fieldJacketFW2.setText("퇴각");
                deckJacket1.setText("퇴각");
                deckJacket2.setText("퇴각");
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("퇴각");
                duckPadding2.setText("퇴각");
                n3b1.setText("퇴각");
                n3b2.setText("퇴각");

                blouson1.setTextColor(Color.BLUE);
                blouson2.setTextColor(Color.BLUE);
                blazerSS1.setTextColor(Color.BLUE);
                blazerSS2.setTextColor(Color.BLUE);
                blazerFW1.setTextColor(Color.RED);
                blazerFW2.setTextColor(Color.RED);
                leatherJacket1.setTextColor(Color.BLUE);
                leatherJacket2.setTextColor(Color.BLUE);
                mustang1.setTextColor(Color.RED);
                mustang2.setTextColor(Color.RED);
                coatSS1.setTextColor(Color.BLUE);
                coatSS2.setTextColor(Color.BLUE);
                coatFW1.setTextColor(Color.RED);
                coatFW2.setTextColor(Color.RED);
                paddingVest1.setTextColor(Color.BLUE);
                paddingVest2.setTextColor(Color.BLUE);
                paddingCoat1.setTextColor(Color.RED);
                paddingCoat2.setTextColor(Color.RED);
                fieldJacketSS1.setTextColor(Color.BLUE);
                fieldJacketSS2.setTextColor(Color.BLUE);
                fieldJacketFW1.setTextColor(Color.RED);
                fieldJacketFW2.setTextColor(Color.RED);
                deckJacket1.setTextColor(Color.RED);
                deckJacket2.setTextColor(Color.RED);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.RED);
                duckPadding2.setTextColor(Color.RED);
                n3b1.setTextColor(Color.RED);
                n3b2.setTextColor(Color.RED);
            } else if (high<10&&high>=8) /*초겨울*/ {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("출격");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("퇴각");
                mustang2.setText("퇴각");
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격");
                coatFW2.setText("출격");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격");
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("출격");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("출격");
                deckJacket2.setText("출격");
                litePadding1.setText("출격");
                litePadding2.setText("출격");
                duckPadding1.setText("퇴각");
                duckPadding2.setText("퇴각");
                n3b1.setText("퇴각");
                n3b2.setText("퇴각");

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.RED);
                mustang2.setTextColor(Color.RED);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.BLUE);
                litePadding2.setTextColor(Color.BLUE);
                duckPadding1.setTextColor(Color.RED);
                duckPadding2.setTextColor(Color.RED);
                n3b1.setTextColor(Color.RED);
                n3b2.setTextColor(Color.RED);
            } else if (high<8) {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("출격");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang2.setText("출격");
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격");
                coatFW2.setText("출격");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격");
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("출격");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("출격");
                deckJacket2.setText("출격");
                litePadding1.setText("출격");
                litePadding2.setText("출격");
                duckPadding1.setText("출격\n(조금 더워요)");
                duckPadding1.setGravity(Gravity.CENTER);
                duckPadding2.setText("출격\n(조금 더워요)");
                duckPadding2.setGravity(Gravity.CENTER);
                n3b1.setText("출격\n(조금 더워요)");
                n3b1.setGravity(Gravity.CENTER);
                n3b2.setText("출격\n(조금 더워요)");
                n3b2.setGravity(Gravity.CENTER);

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.BLUE);
                litePadding2.setTextColor(Color.BLUE);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.BLUE);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.BLUE);
            }
        } else if(low<5&&low>=0){

            if(high>=12) {
                blouson1.setText("출격\n(살짝추워여)");;
                blouson2.setText("출격");
                blazerSS1.setText("출격\n(살짝추워여)");
                blazerSS2.setText("출격");
                blazerFW1.setText("출격");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang2.setText("출격");
                coatSS1.setText("출격\n(살짝추워여)");
                coatSS2.setText("출격");
                coatFW1.setText("출격");
                coatFW2.setText("출격");
                paddingVest1.setText("출격\n(살짝추워여)");
                paddingVest2.setText("출격");
                paddingCoat1.setText("출격");
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("출격\n(살짝추워여)");
                fieldJacketSS2.setText("출격");
                fieldJacketFW1.setText("출격");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("출격");
                deckJacket2.setText("출격");
                litePadding1.setText("출격\n(살짝추워여)");
                litePadding2.setText("출격");
                duckPadding1.setText("출격");
                duckPadding2.setText("퇴각\n(겨땀남)");
                n3b1.setText("출격");
                n3b2.setText("퇴각\n(겨땀남)");

                blouson1.setGravity(Gravity.CENTER);
                blazerSS1.setGravity(Gravity.CENTER);
                coatSS1.setGravity(Gravity.CENTER);
                paddingVest1.setGravity(Gravity.CENTER);
                fieldJacketSS1.setGravity(Gravity.CENTER);
                litePadding1.setGravity(Gravity.CENTER);
                duckPadding2.setGravity(Gravity.CENTER);
                n3b2.setGravity(Gravity.CENTER);

                blouson1.setTextColor(Color.BLUE);
                blouson2.setTextColor(Color.BLUE);
                blazerSS1.setTextColor(Color.BLUE);
                blazerSS2.setTextColor(Color.BLUE);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.BLUE);
                coatSS2.setTextColor(Color.BLUE);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.BLUE);
                paddingVest2.setTextColor(Color.BLUE);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.BLUE);
                fieldJacketSS2.setTextColor(Color.BLUE);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.BLUE);
                litePadding2.setTextColor(Color.BLUE);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.RED);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.RED);

            } else {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("출격");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang2.setText("출격");
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격");
                coatFW2.setText("출격");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격");
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("출격");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("출격");
                deckJacket2.setText("출격");
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("출격");
                duckPadding2.setText("출격");
                n3b1.setText("출격");
                n3b2.setText("출격");

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.BLUE);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.BLUE);
            }
        } else if (low<0&&low>=-6) /*한겨울*/ {

            if(high>=12) { //봄되갈떄
                blouson1.setText("출격\n(살짝추워여)");
                blouson2.setText("출격");
                blazerSS1.setText("출격\n(살짝추워여)");
                blazerSS2.setText("출격)");
                blazerFW1.setText("출격");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang2.setText("출격");
                coatSS1.setText("출격\n(살짝추워여)");
                coatSS2.setText("출격");
                coatFW1.setText("출격");
                coatFW2.setText("출격");
                paddingVest1.setText("출격\n(살짝추워여)");
                paddingVest2.setText("출격");
                paddingCoat1.setText("출격");
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("출격\n(살짝추워여)");
                fieldJacketSS2.setText("출격");
                fieldJacketFW1.setText("출격");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("출격");
                deckJacket2.setText("출격");
                litePadding1.setText("출격");
                litePadding2.setText("출격");
                duckPadding1.setText("출격");
                duckPadding2.setText("퇴각");
                n3b1.setText("출격");
                n3b2.setText("퇴각");

                blouson1.setGravity(Gravity.CENTER);
                blazerSS1.setGravity(Gravity.CENTER);
                coatSS1.setGravity(Gravity.CENTER);
                paddingVest1.setGravity(Gravity.CENTER);
                fieldJacketSS1.setGravity(Gravity.CENTER);
                litePadding1.setGravity(Gravity.CENTER);
                duckPadding2.setGravity(Gravity.CENTER);
                n3b2.setGravity(Gravity.CENTER);

                blouson1.setTextColor(Color.BLUE);
                blouson2.setTextColor(Color.BLUE);
                blazerSS1.setTextColor(Color.BLUE);
                blazerSS2.setTextColor(Color.BLUE);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.BLUE);
                coatSS2.setTextColor(Color.BLUE);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.BLUE);
                paddingVest2.setTextColor(Color.BLUE);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.BLUE);
                fieldJacketSS2.setTextColor(Color.BLUE);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.BLUE);
                litePadding2.setTextColor(Color.BLUE);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.RED);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.RED);
            }
            else if(high<12&&high>=5)/*추운데 낮은 괜춘할 때*/ {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("퇴각");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang1.setGravity(Gravity.CENTER);
                mustang2.setText("출격\n(속 두툼하게)");
                mustang2.setGravity(Gravity.CENTER);
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격\n(최대한 껴입길)");
                coatFW1.setGravity(Gravity.CENTER);
                coatFW2.setText("출격");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격\n(최대한 껴입길)");
                paddingCoat1.setGravity(Gravity.CENTER);
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("출격(속 도툼하게)");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("퇴각");
                deckJacket1.setGravity(Gravity.CENTER);
                deckJacket2.setText("퇴각");
                deckJacket2.setGravity(Gravity.CENTER);
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("출격");
                duckPadding2.setText("출격");
                n3b1.setText("출격");
                n3b2.setText("출격");

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.RED);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.RED);
                deckJacket2.setTextColor(Color.RED);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.BLUE);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.BLUE);
            } else {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("출격\n(속 두툼하게)");
                blazerFW1.setGravity(Gravity.CENTER);
                blazerFW2.setText("출격\n(속 두툼하게)");
                blazerFW2.setGravity(Gravity.CENTER);
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격\n(속 두툼하게)");
                mustang1.setGravity(Gravity.CENTER);
                mustang2.setText("출격\n(속 두툼하게)");
                mustang2.setGravity(Gravity.CENTER);
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격\n(속 두툼하게)");
                coatFW1.setGravity(Gravity.CENTER);
                coatFW2.setText("출격\n(속 두툼하게)");
                coatFW2.setGravity(Gravity.CENTER);
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격\n(속 두툼하게)");
                paddingCoat1.setGravity(Gravity.CENTER);
                paddingCoat2.setText("출격\n(속 두툼하게)");
                paddingCoat2.setGravity(Gravity.CENTER);
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("출격\n(속 두툼하게)");
                fieldJacketFW1.setGravity(Gravity.CENTER);
                fieldJacketFW2.setText("출격\n(속 두툼하게)");
                fieldJacketFW2.setGravity(Gravity.CENTER);
                deckJacket1.setText("출격\n(속 두툼하게)");
                deckJacket1.setGravity(Gravity.CENTER);
                deckJacket2.setText("출격\n(속 두툼하게)");
                deckJacket2.setGravity(Gravity.CENTER);
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("출격");
                duckPadding2.setText("출격");
                n3b1.setText("출격");
                n3b2.setText("출격");

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.BLUE);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.BLUE);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.BLUE);
                deckJacket2.setTextColor(Color.BLUE);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.BLUE);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.BLUE);
            }

        } else if( low < -6) /*한파, 졸라추울떄*/{
            blouson1.setText("퇴각");
            blouson2.setText("퇴각");
            blazerSS1.setText("퇴각");
            blazerSS2.setText("퇴각");
            blazerFW1.setText("퇴각");
            blazerFW2.setText("퇴각");
            leatherJacket1.setText("퇴각");
            leatherJacket2.setText("퇴각");
            mustang1.setText("출격\n(속 두툼하게)");
            mustang1.setGravity(Gravity.CENTER);
            mustang2.setText("출격\n(속 두툼하게)");
            mustang2.setGravity(Gravity.CENTER);
            coatSS1.setText("퇴각");
            coatSS2.setText("퇴각");
            coatFW1.setText("출격\n(최대한 껴입길)");
            coatFW1.setGravity(Gravity.CENTER);
            coatFW2.setText("출격\n(최대한 껴입길)");
            coatFW2.setGravity(Gravity.CENTER);
            paddingVest1.setText("퇴각");
            paddingVest2.setText("퇴각");
            paddingCoat1.setText("출격\n(최대한 껴입길)");
            paddingCoat1.setGravity(Gravity.CENTER);
            paddingCoat2.setText("출격\n(최대한 껴입길)");
            paddingCoat2.setGravity(Gravity.CENTER);
            fieldJacketSS1.setText("퇴각");
            fieldJacketSS2.setText("퇴각");
            fieldJacketFW1.setText("퇴각");
            fieldJacketFW2.setText("퇴각");
            deckJacket1.setText("퇴각");
            deckJacket1.setGravity(Gravity.CENTER);
            deckJacket2.setText("퇴각");
            deckJacket2.setGravity(Gravity.CENTER);
            litePadding1.setText("퇴각");
            litePadding2.setText("퇴각");
            duckPadding1.setText("출격");
            duckPadding2.setText("출격");
            n3b1.setText("출격");
            n3b2.setText("출격");

            blouson1.setTextColor(Color.RED);
            blouson2.setTextColor(Color.RED);
            blazerSS1.setTextColor(Color.RED);
            blazerSS2.setTextColor(Color.RED);
            blazerFW1.setTextColor(Color.RED);
            blazerFW2.setTextColor(Color.RED);
            leatherJacket1.setTextColor(Color.RED);
            leatherJacket2.setTextColor(Color.RED);
            mustang1.setTextColor(Color.BLUE);
            mustang2.setTextColor(Color.BLUE);
            coatSS1.setTextColor(Color.RED);
            coatSS2.setTextColor(Color.RED);
            coatFW1.setTextColor(Color.BLUE);
            coatFW2.setTextColor(Color.BLUE);
            paddingVest1.setTextColor(Color.RED);
            paddingVest2.setTextColor(Color.RED);
            paddingCoat1.setTextColor(Color.BLUE);
            paddingCoat2.setTextColor(Color.BLUE);
            fieldJacketSS1.setTextColor(Color.RED);
            fieldJacketSS2.setTextColor(Color.RED);
            fieldJacketFW1.setTextColor(Color.RED);
            fieldJacketFW2.setTextColor(Color.RED);
            deckJacket1.setTextColor(Color.RED);
            deckJacket2.setTextColor(Color.RED);
            litePadding1.setTextColor(Color.RED);
            litePadding2.setTextColor(Color.RED);
            duckPadding1.setTextColor(Color.BLUE);
            duckPadding2.setTextColor(Color.BLUE);
            n3b1.setTextColor(Color.BLUE);
            n3b2.setTextColor(Color.BLUE);

            if(high>=5)/*추운데 낮은 괜춘할 때*/ {
                blouson1.setText("퇴각");
                blouson2.setText("퇴각");
                blazerSS1.setText("퇴각");
                blazerSS2.setText("퇴각");
                blazerFW1.setText("퇴각");
                blazerFW2.setText("출격");
                leatherJacket1.setText("퇴각");
                leatherJacket2.setText("퇴각");
                mustang1.setText("출격");
                mustang1.setGravity(Gravity.CENTER);
                mustang2.setText("출격\n(속 두툼하게)");
                mustang2.setGravity(Gravity.CENTER);
                coatSS1.setText("퇴각");
                coatSS2.setText("퇴각");
                coatFW1.setText("출격\n(최대한 껴입길)");
                coatFW1.setGravity(Gravity.CENTER);
                coatFW2.setText("출격");
                paddingVest1.setText("퇴각");
                paddingVest2.setText("퇴각");
                paddingCoat1.setText("출격\n(최대한 껴입길)");
                paddingCoat1.setGravity(Gravity.CENTER);
                paddingCoat2.setText("출격");
                fieldJacketSS1.setText("퇴각");
                fieldJacketSS2.setText("퇴각");
                fieldJacketFW1.setText("퇴각");
                fieldJacketFW2.setText("출격");
                deckJacket1.setText("퇴각");
                deckJacket1.setGravity(Gravity.CENTER);
                deckJacket2.setText("퇴각");
                deckJacket2.setGravity(Gravity.CENTER);
                litePadding1.setText("퇴각");
                litePadding2.setText("퇴각");
                duckPadding1.setText("출격");
                duckPadding2.setText("출격");
                n3b1.setText("출격");
                n3b2.setText("출격");

                blouson1.setTextColor(Color.RED);
                blouson2.setTextColor(Color.RED);
                blazerSS1.setTextColor(Color.RED);
                blazerSS2.setTextColor(Color.RED);
                blazerFW1.setTextColor(Color.RED);
                blazerFW2.setTextColor(Color.BLUE);
                leatherJacket1.setTextColor(Color.RED);
                leatherJacket2.setTextColor(Color.RED);
                mustang1.setTextColor(Color.BLUE);
                mustang2.setTextColor(Color.BLUE);
                coatSS1.setTextColor(Color.RED);
                coatSS2.setTextColor(Color.RED);
                coatFW1.setTextColor(Color.BLUE);
                coatFW2.setTextColor(Color.BLUE);
                paddingVest1.setTextColor(Color.RED);
                paddingVest2.setTextColor(Color.RED);
                paddingCoat1.setTextColor(Color.BLUE);
                paddingCoat2.setTextColor(Color.BLUE);
                fieldJacketSS1.setTextColor(Color.RED);
                fieldJacketSS2.setTextColor(Color.RED);
                fieldJacketFW1.setTextColor(Color.RED);
                fieldJacketFW2.setTextColor(Color.BLUE);
                deckJacket1.setTextColor(Color.RED);
                deckJacket2.setTextColor(Color.RED);
                litePadding1.setTextColor(Color.RED);
                litePadding2.setTextColor(Color.RED);
                duckPadding1.setTextColor(Color.BLUE);
                duckPadding2.setTextColor(Color.BLUE);
                n3b1.setTextColor(Color.BLUE);
                n3b2.setTextColor(Color.BLUE);
            }
        }

    }

}
